# Generated by Django 5.1.5 on 2025-01-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(blank=True, max_length=20, null=True)),
                ('acc_link', models.URLField(blank=True, max_length=80, null=True)),
                ('acc_email', models.EmailField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='my_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='my_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accounts'),
        ),
    ]
